// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Unavailable HealthResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for TripStatus.
const (
	Active    TripStatus = "active"
	Completed TripStatus = "completed"
)

// Valid indicates whether the value is a known member of the TripStatus enum.
func (e TripStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Completed:
		return true
	default:
		return false
	}
}

// Coordinates Географические координаты WGS 84.
type Coordinates struct {
	// Latitude Example: 59.9398
	Latitude float64 `json:"latitude"`

	// Longitude Example: 30.3146
	Longitude float64 `json:"longitude"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// PositionData defines model for PositionData.
type PositionData struct {
	// Coordinates Географические координаты WGS 84.
	Coordinates Coordinates `json:"coordinates"`

	// RecordedAt Время фиксации координаты на мобильном устройстве.
	RecordedAt time.Time `json:"recorded_at"`
}

// Problem Problem Details for HTTP APIs (RFC 9457) с дополнительным полем code.
type Problem struct {
	Code     string  `json:"code"`
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int32   `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Trip defines model for Trip.
type Trip struct {
	DriverId openapi_types.UUID `json:"driver_id"`

	// EndPoint Географические координаты WGS 84.
	EndPoint       Coordinates        `json:"end_point"`
	FinishedAt     *time.Time         `json:"finished_at,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	LastPositionAt *time.Time         `json:"last_position_at,omitempty"`

	// Price Стоимость поездки в целых рублях. Это учебное упрощение: копейки не используются.
	//
	// Example: 1450
	Price int64 `json:"price"`

	// StartPoint Географические координаты WGS 84.
	StartPoint Coordinates        `json:"start_point"`
	StartedAt  time.Time          `json:"started_at"`
	Status     TripStatus         `json:"status"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// TripData defines model for TripData.
type TripData struct {
	DriverId openapi_types.UUID `json:"driver_id"`

	// EndPoint Географические координаты WGS 84.
	EndPoint Coordinates `json:"end_point"`

	// Price Стоимость поездки в целых рублях. Это учебное упрощение: копейки не используются.
	//
	// Example: 1450
	Price int64 `json:"price"`

	// StartPoint Географические координаты WGS 84.
	StartPoint Coordinates        `json:"start_point"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// TripPosition defines model for TripPosition.
type TripPosition struct {
	// Coordinates Географические координаты WGS 84.
	Coordinates Coordinates `json:"coordinates"`
	Id          int64       `json:"id"`

	// RecordedAt Время фиксации координаты на мобильном устройстве.
	RecordedAt time.Time          `json:"recorded_at"`
	TripId     openapi_types.UUID `json:"trip_id"`
}

// TripPositionsResponse defines model for TripPositionsResponse.
type TripPositionsResponse struct {
	Positions []TripPosition `json:"positions"`
}

// TripStatus defines model for TripStatus.
type TripStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// TripId defines model for TripId.
type TripId = openapi_types.UUID

// BadRequest Problem Details for HTTP APIs (RFC 9457) с дополнительным полем code.
type BadRequest = Problem

// CreateTripConflict Problem Details for HTTP APIs (RFC 9457) с дополнительным полем code.
type CreateTripConflict = Problem

// InternalError Problem Details for HTTP APIs (RFC 9457) с дополнительным полем code.
type InternalError = Problem

// TripCompleted Problem Details for HTTP APIs (RFC 9457) с дополнительным полем code.
type TripCompleted = Problem

// TripNotFound Problem Details for HTTP APIs (RFC 9457) с дополнительным полем code.
type TripNotFound = Problem

// CreateTripParams defines parameters for CreateTrip.
type CreateTripParams struct {
	// IdempotencyKey Ключ идемпотентности, генерирует клиент. Повторный запрос с тем же ключом и тем же телом возвращает уже созданную поездку и 200, с тем же ключом и другим телом — 409 idempotency_conflict. Заголовок относится к заданию со звёздочкой лабораторной работы 1, в основной части можно игнорировать.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = TripData

// CreateTripPositionJSONRequestBody defines body for CreateTripPosition for application/json ContentType.
type CreateTripPositionJSONRequestBody = PositionData

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateTrip Создать поездку
	// (POST /api/v1/trips)
	CreateTrip(w http.ResponseWriter, r *http.Request, params CreateTripParams)
	// GetTrip Получить поездку
	// (GET /api/v1/trips/{tripId})
	GetTrip(w http.ResponseWriter, r *http.Request, tripId TripId)
	// FinishTrip Завершить поездку
	// (POST /api/v1/trips/{tripId}/finish)
	FinishTrip(w http.ResponseWriter, r *http.Request, tripId TripId)
	// ListTripPositions Получить маршрут поездки
	// (GET /api/v1/trips/{tripId}/positions)
	ListTripPositions(w http.ResponseWriter, r *http.Request, tripId TripId)
	// CreateTripPosition Сохранить координату поездки
	// (POST /api/v1/trips/{tripId}/positions)
	CreateTripPosition(w http.ResponseWriter, r *http.Request, tripId TripId)
	// Health Liveness
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
	// Ready Readiness
	// (GET /ready)
	Ready(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// CreateTrip Создать поездку
// (POST /api/v1/trips)
func (_ Unimplemented) CreateTrip(w http.ResponseWriter, r *http.Request, params CreateTripParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetTrip Получить поездку
// (GET /api/v1/trips/{tripId})
func (_ Unimplemented) GetTrip(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// FinishTrip Завершить поездку
// (POST /api/v1/trips/{tripId}/finish)
func (_ Unimplemented) FinishTrip(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListTripPositions Получить маршрут поездки
// (GET /api/v1/trips/{tripId}/positions)
func (_ Unimplemented) ListTripPositions(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateTripPosition Сохранить координату поездки
// (POST /api/v1/trips/{tripId}/positions)
func (_ Unimplemented) CreateTripPosition(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health Liveness
// (GET /health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ready Readiness
// (GET /ready)
func (_ Unimplemented) Ready(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTripParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrip operation middleware
func (siw *ServerInterfaceWrapper) GetTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinishTrip operation middleware
func (siw *ServerInterfaceWrapper) FinishTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinishTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripPositions operation middleware
func (siw *ServerInterfaceWrapper) ListTripPositions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripPositions(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTripPosition operation middleware
func (siw *ServerInterfaceWrapper) CreateTripPosition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTripPosition(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ready operation middleware
func (siw *ServerInterfaceWrapper) Ready(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ready(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/trips", wrapper.CreateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/trips/{tripId}", wrapper.GetTrip)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/trips/{tripId}/finish", wrapper.FinishTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.Ready)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/trips/{tripId}/positions", wrapper.ListTripPositions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/trips/{tripId}/positions", wrapper.CreateTripPosition)
	})

	return r
}
